# Generated by Django 2.2.28 on 2022-08-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0017_auto_20201024_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostas',
            name='aposta_empate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultado',
            name='empate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rodada',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
