# Generated by Django 2.2.28 on 2022-08-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0018_auto_20220816_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apostas',
            name='aposta_placar_casa',
        ),
        migrations.RemoveField(
            model_name='apostas',
            name='aposta_placar_vistante',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apostou',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='placarCasa',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='placarVisitante',
        ),
    ]
