# Generated by Django 4.0.6 on 2022-08-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0020_profile_pix_alter_profile_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qtde_apostas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='qtde_vitorias',
            field=models.IntegerField(default=0),
        ),
    ]
